<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A monthly work-time report per employee, generated by the
 * MonthlyReportEngineService. The report is regenerated from live data
 * until the admin approves it; `approved_at` freezes the snapshot so no
 * retroactive change can silently alter a settled payroll report.
 */
class MonthlyReport extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'year',
        'month',
        'fix_paid_hours',
        'fix_actual_hours',
        'extra_work_hours',
        'extra_travel_hours',
        'extra_paid_hours',
        'extra_actual_hours',
        'total_paid_hours',
        'snapshot',
        'approved_at',
        'approved_by',
    ];

    protected function casts(): array
    {
        return [
            'fix_paid_hours'      => 'decimal:2',
            'fix_actual_hours'    => 'decimal:2',
            'extra_work_hours'    => 'decimal:2',
            'extra_travel_hours'  => 'decimal:2',
            'extra_paid_hours'    => 'decimal:2',
            'extra_actual_hours'  => 'decimal:2',
            'total_paid_hours'    => 'decimal:2',
            'snapshot'            => 'array',
            'approved_at'         => 'datetime',
        ];
    }

    // ── Relationships ──────────────────────────────────────────────────────

    public function employee(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function approver(): BelongsTo
    {
        return $this->belongsTo(User::class, 'approved_by');
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    public function isApproved(): bool
    {
        return $this->approved_at !== null;
    }

    public function monthLabel(): string
    {
        return $this->periodLabel();
    }

    public function periodLabel(): string
    {
        $date = \Carbon\CarbonImmutable::create($this->year, $this->month, 1);

        return ucfirst($date->locale('de')->translatedFormat('F Y'));
    }
}